version: "3.9"

services: 
  mysql1:
    image: mysql:latest
    restart: always
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: 
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
  
  app:
    build: .
    environment:
      DB_HOST: mysql
      DB_PORT: 3306x
      DB_USER: root
      DB_PASSWORD: secret
    ports:
      - "3000:3000"
    depends_on:
      - mysql1
              
  