version: "3.9"

networks:
  routings:

services: 
  frontend:
    build: .
    ports:
      - "30:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - database
    # command: npx create-react-app
    networks:
      - routings
    stdin_open: true
    tty: true

  backend:
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - routings
    stdin_open: true
    tty: true

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - routings
    stdin_open: true
    tty: true

  

    







              
  